In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
from sklearn import preprocessing
data1=pd.read_csv('data (1).csv')

In [5]:
data1.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

            ...             radius_worst  texture_worst  perimeter_worst  \
0           ...                    25.38          17.33           184.60   
1           ...                    24.99          23.41           158.80   
2           ...                    23.57          25.53           152.50   
3           ...                    14.91          26.50            98.87   
4           ...                    22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 32 columns]

In [6]:
data1.shape

(569, 32)

In [7]:
#drop the first column as it is identifier
data1=data1.drop(['id'],axis=1)

In [8]:
data1.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean           ...             radius_worst  texture_worst  \
0         0.2419           ...                    25.38          17.33   
1         0.1812           ...                    24.99          23.41   
2         0.2069           ...                    23.57          25.53   
3         0.2597           ...                    14.91          26.50   
4         0.1809           ...                    22.54          16.67   

   perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0           184.60      2019.0            0.1622             0.6656   
1           158.80      1956.0            0.1238             0.1866   
2           152.50      1709.0            0.1444             0.4245   
3            98.87       567.7            0.2098             0.8663   
4           152.20      1575.0            0.1374             0.2050   

   concavity_worst  concave points_worst  symmetry_worst  \
0           0.7119                0.2654          0.4601   
1           0.2416                0.1860          0.2750   
2           0.4504                0.2430          0.3613   
3           0.6869                0.2575          0.6638   
4           0.4000                0.1625          0.2364   

   fractal_dimension_worst  
0                  0.11890  
1                  0.08902  
2                  0.08758  
3                  0.17300  
4                  0.07678  

[5 rows x 31 columns]

In [9]:
#examine the target varaiable 'dignosis' which is the variable to predict 
#get a count of diagnosis observations by type
data1.diagnosis.value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

In [10]:
#recode the target variable 'diagosis' to certain the labels 'malignant' and 'benign'
data1['diagnosis'].replace(['M','B'],['Malignant','Benign'])

0      Malignant
1      Malignant
2      Malignant
3      Malignant
4      Malignant
5      Malignant
6      Malignant
7      Malignant
8      Malignant
9      Malignant
10     Malignant
11     Malignant
12     Malignant
13     Malignant
14     Malignant
15     Malignant
16     Malignant
17     Malignant
18     Malignant
19        Benign
20        Benign
21        Benign
22     Malignant
23     Malignant
24     Malignant
25     Malignant
26     Malignant
27     Malignant
28     Malignant
29     Malignant
         ...    
539       Benign
540       Benign
541       Benign
542       Benign
543       Benign
544       Benign
545       Benign
546       Benign
547       Benign
548       Benign
549       Benign
550       Benign
551       Benign
552       Benign
553       Benign
554       Benign
555       Benign
556       Benign
557       Benign
558       Benign
559       Benign
560       Benign
561       Benign
562    Malignant
563    Malignant
564    Malignant
565    Malignant
566    Maligna

In [11]:
#Get summary of parameters
x=data1.loc[:,['radius_mean','area_mean','smoothness_mean']]
x


radius_mean  area_mean  smoothness_mean
0         17.990     1001.0          0.11840
1         20.570     1326.0          0.08474
2         19.690     1203.0          0.10960
3         11.420      386.1          0.14250
4         20.290     1297.0          0.10030
5         12.450      477.1          0.12780
6         18.250     1040.0          0.09463
7         13.710      577.9          0.11890
8         13.000      519.8          0.12730
9         12.460      475.9          0.11860
10        16.020      797.8          0.08206
11        15.780      781.0          0.09710
12        19.170     1123.0          0.09740
13        15.850      782.7          0.08401
14        13.730      578.3          0.11310
15        14.540      658.8          0.11390
16        14.680      684.5          0.09867
17        16.130      798.8          0.11700
18        19.810     1260.0          0.09831
19        13.540      566.3          0.09779
20        13.080      520.0          0.10750
21         9.504      273.9          0.10240
22        15.340      704.4          0.10730
23        21.160     1404.0          0.09428
24        16.650      904.6          0.11210
25        17.140      912.7          0.11860
26        14.580      644.8          0.10540
27        18.610     1094.0          0.09440
28        15.300      732.4          0.10820
29        17.570      955.1          0.09847
..           ...        ...              ...
539        7.691      170.4          0.08668
540       11.540      402.9          0.09984
541       14.470      656.4          0.08837
542       14.740      668.6          0.08275
543       13.210      538.4          0.08671
544       13.870      584.8          0.09578
545       13.620      573.2          0.09246
546       10.320      324.9          0.09434
547       10.260      320.8          0.08877
548        9.683      285.7          0.08491
549       10.820      361.6          0.08192
550       10.860      360.5          0.07431
551       11.130      378.4          0.09566
552       12.770      507.9          0.08276
553        9.333      264.0          0.09240
554       12.880      514.3          0.08123
555       10.290      321.4          0.09030
556       10.160      311.7          0.10030
557        9.423      271.3          0.08123
558       14.590      657.1          0.08473
559       11.510      403.5          0.09261
560       14.050      600.4          0.09929
561       11.200      386.0          0.07449
562       15.220      716.9          0.10480
563       20.920     1347.0          0.10990
564       21.560     1479.0          0.11100
565       20.130     1261.0          0.09780
566       16.600      858.1          0.08455
567       20.600     1265.0          0.11780
568        7.760      181.0          0.05263

[569 rows x 3 columns]

In [12]:
x.describe()

radius_mean    area_mean  smoothness_mean
count   569.000000   569.000000       569.000000
mean     14.127292   654.889104         0.096360
std       3.524049   351.914129         0.014064
min       6.981000   143.500000         0.052630
25%      11.700000   420.300000         0.086370
50%      13.370000   551.100000         0.095870
75%      15.780000   782.700000         0.105300
max      28.110000  2501.000000         0.163400

In [13]:
x=data1.iloc[:,1:31]
y=data1.iloc[:,0]

In [14]:
x.head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   fractal_dimension_mean           ...             radius_worst  \
0                 0.07871           ...                    25.38   
1                 0.05667           ...                    24.99   
2                 0.05999           ...                    23.57   
3                 0.09744           ...                    14.91   
4                 0.05883           ...                    22.54   

   texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0          17.33           184.60      2019.0            0.1622   
1          23.41           158.80      1956.0            0.1238   
2          25.53           152.50      1709.0            0.1444   
3          26.50            98.87       567.7            0.2098   
4          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  
0                  0.11890  
1                  0.08902  
2                  0.08758  
3                  0.17300  
4                  0.07678  

[5 rows x 30 columns]

In [15]:
y.head()

0    M
1    M
2    M
3    M
4    M
Name: diagnosis, dtype: object

In [16]:
#apply normalization to rescale the features to a standard range of values.
#normalize the numeric variable fromm column2 to column 31 in the data frame
minmax=preprocessing.MinMaxScaler(feature_range=(0,1))
minmax.fit(x).transform(x)

array([[0.52103744, 0.0226581 , 0.54598853, ..., 0.91202749, 0.59846245,
        0.41886396],
       [0.64314449, 0.27257355, 0.61578329, ..., 0.63917526, 0.23358959,
        0.22287813],
       [0.60149557, 0.3902604 , 0.59574321, ..., 0.83505155, 0.40370589,
        0.21343303],
       ...,
       [0.45525108, 0.62123774, 0.44578813, ..., 0.48728522, 0.12872068,
        0.1519087 ],
       [0.64456434, 0.66351031, 0.66553797, ..., 0.91065292, 0.49714173,
        0.45231536],
       [0.03686876, 0.50152181, 0.02853984, ..., 0.        , 0.25744136,
        0.10068215]])

In [17]:
#Splitting the dataset into training set and test set
from sklearn import cross_validation, neighbors
from sklearn.cross_validation import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

C:\Users\lenovo\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [18]:
x_train

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
60        10.170         14.88           64.55      311.9          0.11340   
12        19.170         24.80          132.40     1123.0          0.09740   
40        13.440         21.58           86.18      563.0          0.08162   
122       24.250         20.20          166.20     1761.0          0.14470   
220       13.650         13.16           87.88      568.9          0.09646   
268       12.870         16.21           82.38      512.2          0.09425   
550       10.860         21.48           68.51      360.5          0.07431   
212       28.110         18.47          188.50     2499.0          0.11420   
88        12.360         21.80           79.78      466.1          0.08772   
441       17.270         25.42          112.40      928.8          0.08331   
460       17.080         27.15          111.20      930.9          0.09898   
146       11.800         16.58           78.99      432.0          0.10910   
307        9.000         14.40           56.36      246.3          0.07005   
259       15.530         33.56          103.70      744.9          0.10630   
201       17.540         19.32          115.10      951.6          0.08968   
226       10.440         15.46           66.62      329.6          0.10530   
115       11.930         21.53           76.53      438.6          0.09768   
205       15.120         16.68           98.78      716.6          0.08876   
170       12.320         12.39           78.85      464.1          0.10280   
61         8.598         20.98           54.66      221.8          0.12430   
341        9.606         16.84           61.64      280.5          0.08481   
330       16.030         15.51          105.80      793.2          0.09491   
191       12.770         21.41           82.02      507.4          0.08749   
511       14.810         14.70           94.66      680.7          0.08472   
89        14.640         15.24           95.77      651.9          0.11320   
372       21.370         15.10          141.30     1386.0          0.10010   
493       12.460         12.83           78.83      477.3          0.07372   
251       11.500         18.45           73.28      407.4          0.09345   
488       11.680         16.17           75.49      420.5          0.11280   
536       14.270         22.55           93.77      629.8          0.10380   
..           ...           ...             ...        ...              ...   
244       19.400         23.50          129.10     1155.0          0.10270   
112       14.260         19.65           97.83      629.9          0.07837   
387       13.880         16.16           88.37      596.6          0.07026   
303       10.490         18.61           66.86      334.3          0.10680   
79        12.860         18.00           83.19      506.3          0.09934   
254       19.450         19.33          126.50     1169.0          0.10350   
87        19.020         24.59          122.00     1076.0          0.09029   
84        12.000         15.65           76.95      443.3          0.09723   
174       10.660         15.15           67.49      349.6          0.08792   
5         12.450         15.70           82.57      477.1          0.12780   
304       11.460         18.16           73.59      403.1          0.08853   
47        13.170         18.66           85.98      534.6          0.11580   
82        25.220         24.91          171.50     1878.0          0.10630   
547       10.260         16.58           65.85      320.8          0.08877   
263       15.610         19.38          100.00      758.6          0.07840   
273        9.742         15.67           61.50      289.9          0.09037   
128       15.100         16.39           99.58      674.5          0.11500   
55        11.520         18.75           73.34      409.0          0.09524   
319       12.430         17.00           78.60      477.3          0.07557   
216       11.890         18

In [19]:
y_train

60     B
12     M
40     M
122    M
220    B
268    B
550    B
212    M
88     B
441    M
460    M
146    M
307    B
259    M
201    M
226    B
115    B
205    M
170    B
61     B
341    B
330    M
191    B
511    B
89     B
372    M
493    B
251    B
488    B
536    M
      ..
244    M
112    B
387    B
303    B
79     B
254    M
87     M
84     B
174    B
5      M
304    B
47     M
82     M
547    B
263    M
273    B
128    B
55     B
319    B
216    B
283    M
295    B
532    B
58     B
186    M
154    B
427    B
438    B
388    B
458    B
Name: diagnosis, Length: 455, dtype: object

In [20]:
x_test.head

<bound method NDFrame.head of      radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
74        12.310         16.52           79.19      470.9          0.09172   
163       12.340         22.22           79.85      464.5          0.10120   
27        18.610         20.25          122.10     1094.0          0.09440   
277       18.810         19.98          120.90     1102.0          0.08923   
356       13.050         18.59           85.09      512.0          0.10820   
167       16.780         18.80          109.30      886.3          0.08865   
215       13.860         16.93           90.96      578.9          0.10260   
195       12.910         16.33           82.53      516.4          0.07941   
39        13.480         20.82           88.40      559.2          0.10160   
265       20.730         31.12          135.70     1419.0          0.09469   
211       11.840         18.94           75.51      428.0          0.08871   
237       20.480         21.46    

In [21]:
#Fitting classifier to the training set
clf=neighbors.KNeighborsClassifier()
clf.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [22]:
#Predicting the Test Set results
y_pred=clf.predict(x_test)

In [23]:
y_pred

array(['B', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'M', 'M',
       'M', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'B',
       'B', 'M', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B',
       'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'B', 'B',
       'B', 'M', 'M', 'M', 'M', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B',
       'B', 'M', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'M', 'B',
       'B', 'B', 'B', 'M', 'M', 'M', 'M', 'B', 'B', 'M', 'M', 'B', 'B',
       'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'B',
       'B', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'B'], dtype=object)

In [24]:
y_test

74     B
163    B
27     M
277    M
356    B
167    M
215    M
195    B
39     M
265    M
211    B
237    M
94     M
42     M
177    M
383    B
348    B
243    B
38     M
475    B
312    B
563    M
325    B
414    M
13     M
524    B
97     B
138    M
554    B
308    B
      ..
36     M
360    B
80     B
444    M
7      M
123    B
145    B
45     M
568    B
287    B
452    B
30     M
437    B
292    B
114    B
425    B
33     M
564    M
203    M
474    B
96     B
279    B
495    B
26     M
155    B
343    M
48     B
461    M
187    B
494    B
Name: diagnosis, Length: 114, dtype: object

In [25]:
#Build the Confusion Matrix on the test and train
from sklearn.metrics import confusion_matrix
clf_cm_test=confusion_matrix(y_test,y_pred)
clf_cm_test

array([[67,  4],
       [ 6, 37]], dtype=int64)

In [26]:
#Obtaining Accuracy
accuracy=clf.score(x_test,y_test)

In [27]:
accuracy

0.9122807017543859

In [28]:
#test new data
example_measures=np.array([15.44,12.54,150.9,998,0.2345,0.3452,0.2891,0.1234,0.3421,0.06879,2.076,0.8079,7.274,168.7,0.009786,0.03804,0.04372,0.02785,0.02002,0.007621,28.75,16.44,192.7,2025,0.1723,0.7752,0.7121,0.3421,0.4802,0.1278])
example_measures = example_measures.reshape(1,-1)

In [29]:
prediction=clf.predict(example_measures)

In [30]:
print(prediction)

['M']


# Logistic regression

In [31]:
#perfom logistic regression
from sklearn.linear_model.logistic import LogisticRegression
cls=LogisticRegression(random_state=0)
lr_cls=cls.fit(x_train,y_train)

In [32]:
#Predicting on test and train data
lr_y_test=lr_cls.predict(x_test)
lr_y_test

array(['B', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'M', 'M',
       'M', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'B',
       'B', 'M', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B',
       'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'B', 'B',
       'B', 'M', 'M', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B',
       'B', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'B',
       'B', 'B', 'B', 'M', 'M', 'M', 'M', 'B', 'B', 'M', 'M', 'B', 'B',
       'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'B',
       'B', 'B', 'B', 'M', 'B', 'M', 'B', 'M', 'B', 'B'], dtype=object)

In [33]:
lr_y_train=lr_cls.predict(x_train)
lr_y_train

array(['B', 'M', 'M', 'M', 'B', 'B', 'B', 'M', 'B', 'M', 'M', 'B', 'B',
       'M', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'M',
       'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'M',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B',
       'B', 'B', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'M', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'M',
       'M', 'B', 'M', 'B', 'M', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'B',
       'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'B', 'M', 'M', 'M',
       'B', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'M', 'M',
       'B', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'M', 'M', 'B', 'M',
       'B', 'B', 'M', 'M', 'M', 'B', 'M', 'B', 'M', 'B', 'M', 'M', 'B',
       'B', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'M',
       'B', 'M', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'B

# SUPPORT VECTOR CLASSIFICATION(SVC)

In [34]:
#Support vector classification
from sklearn.svm import SVC
sc =SVC(kernel='rbf')
sc_classifier=sc.fit(x_train,y_train) #model building

In [35]:
#Predicting Test and Train data
svc_y_test=sc_classifier.predict(x_test)
print(svc_y_test)

['B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B'
 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B'
 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B'
 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B'
 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B'
 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B'
 'B' 'B' 'B' 'B' 'B' 'B']


In [36]:
svc_y_train=sc_classifier.predict(x_train) #train
print(svc_y_train)

['B' 'M' 'M' 'M' 'B' 'B' 'B' 'M' 'B' 'M' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'M'
 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'M' 'B' 'M' 'B' 'B' 'M' 'B'
 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'B' 'B'
 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'M' 'B' 'M'
 'B' 'B' 'B' 'M' 'B' 'M' 'B' 'B' 'M' 'B' 'M' 'M' 'B' 'M' 'M' 'M' 'B' 'B'
 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M'
 'M' 'B' 'M' 'B' 'M' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'M' 'B'
 'M' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'M' 'M' 'B' 'M' 'B'
 'B' 'M' 'M' 'M' 'B' 'M' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'M'
 'B' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M'
 'B' 'M' 'B' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'M' 'M' 'M' 'B'
 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'M' 'B' 'M' 'B' 'B' 'B' 'M'
 'M' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M'
 'M' 'B' 'M' 'M' 'M' 'B' 'B' 'M' 'B' 'M' 'B' 'M' 'B

In [37]:
#Build a confusion matrix on test and tarin
from sklearn.metrics import confusion_matrix
svc_cm_test=confusion_matrix(y_test,svc_y_test)
svc_cm_test

array([[71,  0],
       [43,  0]], dtype=int64)

In [38]:
svc_cm_train=confusion_matrix(y_train,svc_y_train)
svc_cm_train

array([[286,   0],
       [  0, 169]], dtype=int64)

In [39]:
#Accuracy classification score
from sklearn.metrics import accuracy_score
svc_acc_test=accuracy_score(y_test,svc_y_test) #for test
svc_acc_test

0.6228070175438597

In [40]:
svc_acc_train=accuracy_score(y_train,svc_y_train) #for train
svc_acc_train

1.0

# DECISION TREE CLASSIFIER

In [41]:
#DECISION TREE CLASSIFIER
from sklearn.tree import DecisionTreeClassifier
dtc_clf=DecisionTreeClassifier()
dtc_clf.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [42]:
#Predicting on test and train data
dtc_y_test=dtc_clf.predict(x_test)
dtc_y_test

array(['B', 'B', 'M', 'M', 'B', 'M', 'M', 'B', 'M', 'M', 'B', 'M', 'M',
       'M', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'B',
       'B', 'M', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B',
       'B', 'M', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'M', 'B', 'B',
       'B', 'M', 'M', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B',
       'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'M', 'B',
       'B', 'B', 'B', 'M', 'M', 'M', 'M', 'B', 'B', 'M', 'M', 'B', 'B',
       'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'B',
       'B', 'B', 'B', 'M', 'B', 'M', 'B', 'M', 'B', 'B'], dtype=object)

In [43]:
dtc_y_train=dtc_clf.predict(x_train)
dtc_y_train

array(['B', 'M', 'M', 'M', 'B', 'B', 'B', 'M', 'B', 'M', 'M', 'M', 'B',
       'M', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'M',
       'B', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'M',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B',
       'B', 'B', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'M', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'M',
       'B', 'B', 'M', 'B', 'M', 'M', 'B', 'M', 'M', 'M', 'B', 'B', 'B',
       'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'M', 'B', 'B', 'M', 'B',
       'B', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'M',
       'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'M',
       'B', 'B', 'M', 'M', 'M', 'B', 'M', 'M', 'M', 'B', 'M', 'M', 'B',
       'B', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'M',
       'B', 'M', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'B

In [44]:
#Build confusion matrix on test and train
from sklearn.metrics import confusion_matrix
dtc_cm_test=confusion_matrix(y_test,dtc_y_test)
dtc_cm_test

array([[68,  3],
       [ 4, 39]], dtype=int64)

In [45]:
#Accuracy score on test and train
from sklearn.metrics import accuracy_score
dtc_accu_test=accuracy_score(y_test,dtc_y_test)
dtc_accu_test

0.9385964912280702

In [46]:
dtc_accu_train=accuracy_score(y_train,dtc_y_train)
dtc_accu_train

1.0

# RANDOM FOREST

In [52]:
#build random forest classifier
from sklearn.ensemble import RandomForestClassifier
rmf=RandomForestClassifier(max_depth=3,random_state=0)
rf_classi=rmf.fit(x,y)

In [53]:
rf_classi=RandomForestClassifier()
rf_classi.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [58]:
rf_classi_y_test=dtc_clf.predict(x_test)
rf_classi_y_test

array(['B', 'B', 'M', 'M', 'B', 'M', 'M', 'B', 'M', 'M', 'B', 'M', 'M',
       'M', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'B',
       'B', 'M', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B',
       'B', 'M', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'M', 'B', 'B',
       'B', 'M', 'M', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B',
       'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'M', 'B',
       'B', 'B', 'B', 'M', 'M', 'M', 'M', 'B', 'B', 'M', 'M', 'B', 'B',
       'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'B',
       'B', 'B', 'B', 'M', 'B', 'M', 'B', 'M', 'B', 'B'], dtype=object)

In [61]:
from sklearn.metrics import confusion_matrix
rf_cm_test=confusion_matrix(y_test,rf_classi_y_test)
rf_cm_test

array([[68,  3],
       [ 4, 39]], dtype=int64)

In [63]:
#Accuracy score on test and trai data
from sklearn.metrics import accuracy_score
rf_accu_test=accuracy_score(y_test,rf_classi_y_test)
rf_accu_test

0.9385964912280702

In [71]:
rf_accu_train= accuracy_score(y_train,y_train)
rf_accu_train

1.0

In [78]:
#Perform AdaBoosting
from sklearn import model_selection
from sklearn.ensemble import AdaBoostClassifier
seed=7
num_trees=30
kfold=model_selection.KFold(n_splits=10,random_state=seed)
model=AdaBoostClassifier(n_estimators=num_trees,random_state=seed)
results=model_selection.cross_val_score(model,x_train,y_train,cv=kfold)
results

array([0.93478261, 0.97826087, 0.82608696, 0.97826087, 0.97826087,
       0.95555556, 0.93333333, 0.95555556, 0.93333333, 0.95555556])

In [79]:
print(results.mean())

0.9428985507246377
